# This is a basic workflow to help you get started with Actions

name: Force rebuild every month

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 16 1 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+10 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :
  build:
    permissions: write-all
    needs: check
    uses: ./.github/workflows/build.yml
    secrets: inherit
